In [135]:
import pandas as pd

In [136]:
df=pd.read_csv("Dataset_1.csv")
df.sample(10)

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
430,NaN,CUST430,NaN,NaN,2023-01-15,Cash,Mumbai,NaN,False
742,ORD1742,NaN,50.0,3500.75,2023-01-15,Debit Card,Mumbai,three,yes
465,ORD1465,user_465,18.0,NaN,2023/03/10,Credit Card,Mumbai,1,True
77,ORD1077,NaN,-3.0,₹999,2023-01-15,NaN,Hyderabad,NaN,NaN
828,NaN,NaN,35.0,₹999,15/02/2023,Cash,mumbai,2,NaN
928,NaN,NaN,35.0,3500.75,2023-01-15,CARD,Delhi,5,NaN
71,NaN,NaN,65.0,499.99,2023/03/10,Debit Card,Mumbai,NaN,False
914,NaN,NaN,NaN,NaN,invalid,Credit Card,Bangalore,1,False
503,ORD1503,user_503,NaN,250.5,2023/03/10,Cash,mumbai,three,NaN
654,NaN,CUST654,NaN,250.5,invalid,Credit Card,Delhi,2,yes

In [137]:
df['order_amount']= pd.to_numeric(df['order_amount'],errors="coerce")
df['order_amount'].isna()

0      False
1      False
2       True
3      False
4      False
       ...
995    False
996     True
997     True
998    False
999     True
Name: order_amount, Length: 1000, dtype: bool

In [138]:
df['is_delivered']=df['is_delivered'].replace({'yes':'true','no':'false','True':'true','False':'false'})
df.sample(10)

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
425,NaN,NaN,NaN,250.50,2023/03/10,Cash,Hyderabad,-1,true
958,ORD1958,user_958,35.0,NaN,invalid,Credit Card,Mumbai,5,true
90,NaN,NaN,NaN,499.99,15/02/2023,CARD,Bangalore,1,true
479,NaN,CUST479,25.0,NaN,2023-01-15,UPI,NaN,1,false
471,ORD1471,NaN,35.0,NaN,2023/03/10,UPI,Bangalore,NaN,false
999,NaN,user_999,120.0,NaN,15/02/2023,Debit Card,NaN,-1,true
97,NaN,user_97,NaN,NaN,invalid,UPI,DELHI,three,false
741,ORD1741,CUST741,50.0,250.50,2023-01-15,UPI,Mumbai,-1,true
151,NaN,NaN,NaN,NaN,15/02/2023,Cash,NaN,2,true
915,ORD1915,NaN,NaN,NaN,15/02/2023,Cash,Delhi,NaN,true

In [139]:
import numpy as np
df['delivery_days']=pd.to_numeric(df['delivery_days'],errors="coerce")
df.loc[(df['delivery_days']<0),'delivery_days']=np.nan

In [140]:
df['city']=df['city'].astype(str).str.title()
df['payment_mode']=df['payment_mode'].astype(str).str.lower()
cc=df.groupby('city')[['payment_mode']].value_counts(normalize=True)*100
cc

city       payment_mode
Bangalore  upi             27.814570
           card            16.556291
           debit card      15.894040
           nan             15.231788
           cash            14.569536
           credit card      9.933775
Delhi      upi             29.470199
           debit card      16.225166
           card            15.894040
           cash            15.231788
           credit card     13.576159
           nan              9.602649
Hyderabad  upi             25.531915
           nan             17.021277
           card            16.312057
           cash            14.184397
           debit card      14.184397
           credit card     12.765957
Mumbai     upi             30.681818
           cash            16.666667
           nan             15.151515
           debit card      13.636364
           credit card     12.121212
           card            11.742424
Nan        upi             30.985915
           cash            18.309859
           card            16.901408
           nan             13.380282
           credit card     11.971831
           debit card       8.450704
Name: proportion, dtype: float64

In [141]:
df['city']=df['city'].astype(str).str.strip().str.title()
df['payment_mode']=df['payment_mode'].astype(str).str.strip().str.lower()
cc=df.groupby('city')[['payment_mode','city']].value_counts(normalize=True)*100
cc

city       payment_mode
Bangalore  upi             27.814570
           card            16.556291
           debit card      15.894040
           nan             15.231788
           cash            14.569536
           credit card      9.933775
Delhi      upi             29.470199
           debit card      16.225166
           card            15.894040
           cash            15.231788
           credit card     13.576159
           nan              9.602649
Hyderabad  upi             25.531915
           nan             17.021277
           card            16.312057
           cash            14.184397
           debit card      14.184397
           credit card     12.765957
Mumbai     upi             30.681818
           cash            16.666667
           nan             15.151515
           debit card      13.636364
           credit card     12.121212
           card            11.742424
Nan        upi             30.985915
           cash            18.309859
           card            16.901408
           nan             13.380282
           credit card     11.971831
           debit card       8.450704
Name: proportion, dtype: float64

In [142]:
df

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.50,2023-01-15,debit card,Nan,5.0,true
1,ORD1001,NaN,18.0,1200.00,2023/03/10,debit card,Nan,5.0,true
2,ORD1002,CUST2,35.0,NaN,NaN,nan,Mumbai,7.0,true
3,ORD1003,user_3,35.0,1200.00,2023-01-15,cash,Nan,NaN,false
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,card,Nan,NaN,true
...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,3500.75,15/02/2023,upi,Mumbai,1.0,true
996,NaN,CUST996,18.0,NaN,2023-01-15,credit card,Hyderabad,2.0,true
997,NaN,user_997,50.0,NaN,2023/03/10,cash,Delhi,1.0,NaN
998,ORD1998,NaN,65.0,1200.00,2023-01-15,nan,Mumbai,2.0,false
999,NaN,user_999,120.0,NaN,15/02/2023,debit card,Nan,NaN,true

In [143]:
df['customer_age']=pd.to_numeric(df['customer_age'],errors='coerce')
df['order_amount']=pd.to_numeric(df['order_amount'],errors='coerce')
x=df['order_amount'].median()
x
df[(df['customer_age'].isna()) & (df['order_amount']>x)]

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
5,NaN,NaN,NaN,1200.00,2023-01-15,card,Mumbai,1.0,false
37,NaN,NaN,NaN,3500.75,15/02/2023,card,Mumbai,7.0,NaN
44,ORD1044,NaN,NaN,3500.75,15/02/2023,upi,Mumbai,NaN,true
75,NaN,CUST75,NaN,1200.00,15/02/2023,upi,Delhi,1.0,false
76,NaN,NaN,NaN,3500.75,invalid,nan,Hyderabad,NaN,true
...,...,...,...,...,...,...,...,...,...
895,ORD1895,user_895,NaN,1200.00,15/02/2023,debit card,Bangalore,NaN,true
902,NaN,user_902,NaN,1200.00,NaN,upi,Hyderabad,NaN,true
924,NaN,NaN,NaN,3500.75,2023-01-15,card,Bangalore,NaN,true
930,ORD1930,NaN,NaN,1200.00,NaN,nan,Delhi,1.0,true
989,ORD1989,NaN,NaN,1200.00,2023-01-15,upi,Mumbai,NaN,false

In [144]:
df[(df['customer_id'].duplicated() )]

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
1,ORD1001,NaN,18.0,1200.00,2023/03/10,debit card,Nan,5.0,true
5,NaN,NaN,NaN,1200.00,2023-01-15,card,Mumbai,1.0,false
7,ORD1007,NaN,120.0,NaN,2023-01-15,card,Nan,5.0,false
10,NaN,NaN,65.0,NaN,2023-01-15,credit card,Bangalore,7.0,false
12,ORD1012,NaN,65.0,NaN,invalid,credit card,Delhi,7.0,false
...,...,...,...,...,...,...,...,...,...
990,NaN,NaN,25.0,NaN,15/02/2023,upi,Hyderabad,NaN,true
991,NaN,NaN,-3.0,3500.75,2023/03/10,card,Hyderabad,1.0,true
993,NaN,NaN,18.0,3500.75,NaN,nan,Hyderabad,2.0,true
994,NaN,NaN,NaN,250.50,invalid,debit card,Bangalore,NaN,false
998,ORD1998,NaN,65.0,1200.00,2023-01-15,nan,Mumbai,2.0,false

In [145]:
ucity=df.groupby('customer_id')['city'].nunique()

cust_order = ucity[(ucity>=1)].reset_index()
cust_order

    customer_id  city
0       CUST108     1
1        CUST11     1
2       CUST111     1
3       CUST117     1
4       CUST119     1
..          ...   ...
484     user_97     1
485    user_977     1
486    user_995     1
487    user_997     1
488    user_999     1

[489 rows x 2 columns]

In [146]:
flag=df[ (df['delivery_days'].isna()) & (df['is_delivered']=='true')]
flag

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,card,Nan,NaN,true
17,NaN,NaN,-3.0,NaN,15/02/2023,upi,Hyderabad,NaN,true
21,NaN,NaN,25.0,499.99,NaN,credit card,Mumbai,NaN,true
27,NaN,NaN,25.0,NaN,2023-01-15,nan,Nan,NaN,true
33,ORD1033,user_33,120.0,499.99,15/02/2023,upi,Bangalore,NaN,true
...,...,...,...,...,...,...,...,...,...
979,NaN,NaN,18.0,1200.00,invalid,nan,Hyderabad,NaN,true
980,NaN,CUST980,NaN,250.50,15/02/2023,cash,Bangalore,NaN,true
987,NaN,CUST987,50.0,NaN,2023/03/10,nan,Bangalore,NaN,true
990,NaN,NaN,25.0,NaN,15/02/2023,upi,Hyderabad,NaN,true
999,NaN,user_999,120.0,NaN,15/02/2023,debit card,Nan,NaN,true

In [147]:
df['delivery_flag']=(df['delivery_days'].isna()) & (df['is_delivered'].astype(str).str.lower().isin(['True','true','yes']))
df['delivery_flag']
df[['delivery_days','is_delivered','delivery_flag']]

     delivery_days is_delivered  delivery_flag
0              5.0         true          False
1              5.0         true          False
2              7.0         true          False
3              NaN        false          False
4              NaN         true           True
..             ...          ...            ...
995            1.0         true          False
996            2.0         true          False
997            1.0          NaN          False
998            2.0        false          False
999            NaN         true           True

[1000 rows x 3 columns]

In [148]:
df['payment_mode']=df['payment_mode'].astype(str).str.strip().str.lower()
df.groupby('payment_mode')['order_amount'].mean().reset_index(name="Average_amount")

  payment_mode  Average_amount
0         card     1553.016237
1         cash     1414.393708
2  credit card     1243.262656
3   debit card     1432.739318
4          nan     1606.852208
5          upi     1349.349091

In [149]:
# x=df.groupby('payment_mode')['order_amount'].mean().reset_index(name="Average_amount")
# df[(df['order_date'].isna()) & (x['Average_amount']>30)]

city_missing=df.assign(missing=df['order_date'].isna()).groupby('city')['missing'].mean().mul(100)
city_missing[city_missing>30]

Series([], Name: missing, dtype: float64)