In [217]:
import pandas as pd

In [218]:
df=pd.read_csv("Dataset_1.csv")
df.sample(10)

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
53,NaN,user_53,120.0,3500.75,NaN,Debit Card,Hyderabad,NaN,NaN
434,ORD1434,NaN,65.0,NaN,15/02/2023,Cash,Delhi,three,yes
420,NaN,NaN,NaN,250.5,2023/03/10,CARD,Delhi,NaN,False
432,NaN,NaN,50.0,₹999,2023-01-15,CARD,Mumbai,three,True
581,ORD1581,CUST581,120.0,499.99,invalid,upi,Hyderabad,5,yes
343,ORD1343,NaN,120.0,NaN,NaN,CARD,mumbai,three,True
418,ORD1418,CUST418,NaN,1200,invalid,UPI,Delhi,2,NaN
453,NaN,NaN,NaN,3500.75,2023-01-15,Credit Card,Mumbai,three,no
861,NaN,CUST861,NaN,NaN,2023/03/10,Cash,DELHI,-1,True
467,NaN,NaN,-3.0,NaN,2023/03/10,Cash,Hyderabad,1,False

## 1

In [219]:
# df['order_amount']= pd.to_numeric(df['order_amount'],errors="coerce")
# df['order_amount'].isna()

In [220]:
# df['is_delivered']=df['is_delivered'].replace({'yes':'true','no':'false','True':'true','False':'false'})
# df.sample(10)

In [221]:
df['order_amount']= pd.to_numeric(df['order_amount'],errors="coerce").isna()

In [222]:
df['is_delivered'].astype(str).str.lower().isin(["true","yes"])
df['is_delivered'].astype(str).str.lower().isin(["false","no"])

0      False
1      False
2      False
3       True
4      False
       ...
995    False
996    False
997    False
998     True
999    False
Name: is_delivered, Length: 1000, dtype: bool

In [223]:
df.sample(10)

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
576,NaN,NaN,25.0,False,2023/03/10,Debit Card,mumbai,three,False
188,ORD1188,user_188,18.0,False,2023/03/10,CARD,Delhi,2,NaN
444,NaN,NaN,65.0,True,2023-01-15,Debit Card,Bangalore,three,False
344,NaN,NaN,NaN,False,2023/03/10,Credit Card,Hyderabad,7,True
878,NaN,NaN,120.0,True,2023/03/10,UPI,Delhi,2,False
905,NaN,NaN,35.0,False,2023-01-15,upi,Hyderabad,NaN,NaN
689,NaN,NaN,NaN,False,2023-01-15,UPI,DELHI,three,no
742,ORD1742,NaN,50.0,False,2023-01-15,Debit Card,Mumbai,three,yes
996,NaN,CUST996,18.0,True,2023-01-15,Credit Card,Hyderabad,2,yes
405,ORD1405,CUST405,35.0,True,2023/03/10,Credit Card,Mumbai,-1,True

##

In [224]:
df['order_date']=pd.to_datetime(df['order_date'],errors="coerce",dayfirst=True)
df

C:\Users\DELL\AppData\Local\Temp\ipykernel_23272\1150938491.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['order_date']=pd.to_datetime(df['order_date'],errors="coerce",dayfirst=True)

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,False,2023-01-15,Debit Card,NaN,5,True
1,ORD1001,NaN,18.0,False,NaT,Debit Card,NaN,5,yes
2,ORD1002,CUST2,35.0,True,NaT,NaN,Mumbai,7,yes
3,ORD1003,user_3,35.0,False,2023-01-15,Cash,NaN,three,False
4,ORD1004,user_4,-3.0,False,2023-01-15,CARD,NaN,three,yes
...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,False,NaT,upi,Mumbai,1,True
996,NaN,CUST996,18.0,True,2023-01-15,Credit Card,Hyderabad,2,yes
997,NaN,user_997,50.0,True,NaT,Cash,Delhi,1,NaN
998,ORD1998,NaN,65.0,False,2023-01-15,NaN,Mumbai,2,False
999,NaN,user_999,120.0,True,NaT,Debit Card,NaN,-1,True

In [225]:
import numpy as np
df['delivery_days']=pd.to_numeric(df['delivery_days'],errors="coerce")
# df.loc[(df['delivery_days']<0),'delivery_days']=np.nan

df[(df['order_date'].notna()) & (df['delivery_days']<0)]

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
99,NaN,NaN,50.0,False,2023-01-15,Debit Card,Hyderabad,-1.0,NaN
115,ORD1115,NaN,-3.0,False,2023-01-15,Cash,mumbai,-1.0,False
143,NaN,user_143,25.0,False,2023-01-15,Debit Card,Hyderabad,-1.0,NaN
155,NaN,CUST155,NaN,False,2023-01-15,upi,Delhi,-1.0,yes
170,NaN,NaN,NaN,False,2023-01-15,Cash,DELHI,-1.0,True
238,ORD1238,user_238,NaN,True,2023-01-15,CARD,DELHI,-1.0,False
270,NaN,NaN,35.0,True,2023-01-15,CARD,Delhi,-1.0,False
272,NaN,user_272,65.0,True,2023-01-15,UPI,NaN,-1.0,NaN
303,ORD1303,user_303,35.0,False,2023-01-15,Cash,Hyderabad,-1.0,False
334,NaN,user_334,50.0,False,2023-01-15,upi,Delhi,-1.0,no
407,NaN,NaN,65.0,False,2023-01-15,CARD,DELHI,-1.0,True
429,NaN,user_429,35.0,True,2023-01-15,CARD,NaN,-1.0,NaN
493,NaN,NaN,-3.0,False,2023-01-15,CARD,Hyderabad,-1.0,no
561,NaN,user_561,25.0,False,2023-01-15,upi,DELHI,-1.0,yes
628,NaN,NaN,50.0,True,2023-01-15,upi,Delhi,-1.0,no
639,NaN,CUST639,-3.0,False,2023-01-15,Cash,DELHI,-1.0,no
674,NaN,NaN,18.0,True,2023-01-15,upi,mumbai,-1.0,True
720,ORD1720,NaN,35.0,False,2023-01-15,upi,NaN,-1.0,False
726,NaN,NaN,NaN,False,2023-01-15,upi,Hyderabad,-1.0,no
741,ORD1741,CUST741,50.0,False,2023-01-15,UPI,Mumbai,-1.0,yes
751,ORD1751,NaN,35.0,True,2023-01-15,Cash,Delhi,-1.0,True
763,NaN,NaN,NaN,False,2023-01-15,Debit Card,DELHI,-1.0,NaN
780,ORD1780,NaN,25.0,True,2023-01-15,upi,Hyderabad,-1.0,yes
838,NaN,user_838,NaN,False,2023-01-15,NaN,Mumbai,-1.0,no
880,ORD1880,user_880,35.0,False,2023-01-15,Cash,Mumbai,-1.0,True
934,NaN,NaN,-3.0,True,2023-01-15,UPI,mumbai,-1.0,no
937,ORD1937,CUST937,-3.0,True,2023-01-15,Debit Card,mumbai,-1.0,yes
945,ORD1945,NaN,NaN,False,2023-01-15,NaN,mumbai,-1.0,no

In [226]:
df['city']=df['city'].astype(str).str.strip().str.title()
df['payment_mode']=df['payment_mode'].astype(str).str.strip().str.lower()

x=(
    df.groupby(['city','payment_mode']).size()
)
perc=x/x.groupby(level=0).sum()*100
# perc=pd.DataFrame(perc,columns=(['percentage'])).reset_index()
perc=perc.reset_index(name='percentage')

perc

         city payment_mode  percentage
0   Bangalore         card   16.556291
1   Bangalore         cash   14.569536
2   Bangalore  credit card    9.933775
3   Bangalore   debit card   15.894040
4   Bangalore          nan   15.231788
5   Bangalore          upi   27.814570
6       Delhi         card   15.894040
7       Delhi         cash   15.231788
8       Delhi  credit card   13.576159
9       Delhi   debit card   16.225166
10      Delhi          nan    9.602649
11      Delhi          upi   29.470199
12  Hyderabad         card   16.312057
13  Hyderabad         cash   14.184397
14  Hyderabad  credit card   12.765957
15  Hyderabad   debit card   14.184397
16  Hyderabad          nan   17.021277
17  Hyderabad          upi   25.531915
18     Mumbai         card   11.742424
19     Mumbai         cash   16.666667
20     Mumbai  credit card   12.121212
21     Mumbai   debit card   13.636364
22     Mumbai          nan   15.151515
23     Mumbai          upi   30.681818
24        Nan         card   16.901408
25        Nan         cash   18.309859
26        Nan  credit card   11.971831
27        Nan   debit card    8.450704
28        Nan          nan   13.380282
29        Nan          upi   30.985915

In [227]:
df['customer_age']=pd.to_numeric(df['customer_age'],errors='coerce')
df['order_amount']=pd.to_numeric(df['order_amount'],errors='coerce')
x=df['order_amount'].median()
x
data=df[(df['customer_age'].isna()) & (df['order_amount']>x)]
data

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
9,NaN,user_9,NaN,True,NaT,upi,Delhi,-1.0,no
13,NaN,CUST13,NaN,True,NaT,cash,Mumbai,7.0,False
24,ORD1024,CUST24,NaN,True,NaT,credit card,Delhi,1.0,yes
28,ORD1028,CUST28,NaN,True,NaT,cash,Nan,NaN,NaN
29,NaN,user_29,NaN,True,NaT,debit card,Delhi,7.0,True
...,...,...,...,...,...,...,...,...,...
960,NaN,NaN,NaN,True,NaT,upi,Nan,NaN,False
964,ORD1964,NaN,NaN,True,2023-01-15,upi,Mumbai,7.0,no
976,NaN,NaN,NaN,True,2023-01-15,nan,Mumbai,2.0,no
983,NaN,NaN,NaN,True,NaT,credit card,Mumbai,2.0,False
992,NaN,CUST992,NaN,True,2023-01-15,card,Nan,NaN,False

In [228]:
ucity=df.groupby('customer_id')['city'].nunique()

cust_order = ucity[(ucity>=1)].reset_index()
cust_order

    customer_id  city
0       CUST108     1
1        CUST11     1
2       CUST111     1
3       CUST117     1
4       CUST119     1
..          ...   ...
484     user_97     1
485    user_977     1
486    user_995     1
487    user_997     1
488    user_999     1

[489 rows x 2 columns]

In [229]:
flag=df[ (df['delivery_days'].isna()) & (df['is_delivered']=='True')]
flag

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
17,NaN,NaN,-3.0,True,NaT,upi,Hyderabad,NaN,True
27,NaN,NaN,25.0,True,2023-01-15,nan,Nan,NaN,True
39,NaN,NaN,65.0,True,NaT,debit card,Mumbai,NaN,True
42,NaN,user_42,18.0,True,NaT,nan,Hyderabad,NaN,True
61,NaN,CUST61,NaN,True,2023-01-15,debit card,Mumbai,NaN,True
...,...,...,...,...,...,...,...,...,...
956,NaN,CUST956,50.0,True,NaT,card,Nan,NaN,True
961,ORD1961,user_961,65.0,True,NaT,credit card,Nan,NaN,True
967,NaN,NaN,65.0,True,NaT,nan,Mumbai,NaN,True
980,NaN,CUST980,NaN,False,NaT,cash,Bangalore,NaN,True
990,NaN,NaN,25.0,True,NaT,upi,Hyderabad,NaN,True

In [233]:
df['delivery_flag']=(df['delivery_days'].isna()) & (df['is_delivered'].astype(str).str.lower().isin(['True','true','yes']))
df['delivery_flag'].value_counts()

delivery_flag
False    885
True     115
Name: count, dtype: int64

In [244]:
city_missing=df.assign(missing=df['order_date'].isna()).groupby('city')['missing'].mean().mul(100)
city_missing[city_missing>30]

city
Bangalore    80.794702
Delhi        80.463576
Hyderabad    84.397163
Mumbai       74.242424
Nan          81.690141
Name: missing, dtype: float64