In [154]:
import pandas as pd

In [155]:
df=pd.read_csv("task.csv")
df

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active
0,user_0,-5,₹50000,HR,2020/12/01,DELHI,3,five,True
1,U1001,30,45000,Finance,15/02/2021,Delhi,3,1,yes
2,U1002,30,25000,HR,NaN,Delhi,excellent,10,False
3,NaN,unknown,NaN,HR,invalid,Hyderabad,excellent,5,yes
4,NaN,NaN,120000.75,IT,NaN,DELHI,NaN,-1,False
...,...,...,...,...,...,...,...,...,...
995,NaN,60,₹50000,HR,15/02/2021,DELHI,2,five,NaN
996,U1996,NaN,NaN,IT,15/02/2021,Mumbai,NaN,5,no
997,user_997,unknown,25000,HR,invalid,Mumbai,3,5,True
998,U1998,-5,25000,NaN,15/02/2021,Bangalore,1,0,True
999,NaN,30,45000,HR,2022-01-15,Hyderabad,excellent,five,no

### 1

In [156]:
df.shape

(1000, 9)

In [157]:
df.columns

Index(['user_id', 'age', 'salary', 'department', 'join_date', 'city',
       'performance_score', 'experience_years', 'is_active'],
      dtype='object')

In [158]:
df.dtypes

user_id              object
age                  object
salary               object
department           object
join_date            object
city                 object
performance_score    object
experience_years     object
is_active            object
dtype: object

### 2

In [159]:
df.isnull().mean()*100

user_id              51.0
age                  11.4
salary               31.1
department           14.1
join_date            21.9
city                 14.9
performance_score    10.1
experience_years     12.7
is_active            20.0
dtype: float64

### 3

In [160]:
df.apply(lambda col: col.map(type).nunique())

user_id              2
age                  2
salary               2
department           2
join_date            2
city                 2
performance_score    2
experience_years     2
is_active            2
dtype: int64

### 4

In [161]:
import numpy as np
df['user_id']=df['user_id'].replace('', np.nan).str.upper()

df.sample(10)

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active
744,NaN,NaN,120000.75,Finance,NaN,Mumbai,3,NaN,True
833,NaN,unknown,NaN,NaN,NaN,Delhi,3,10,no
515,NaN,25,78000,Finance,2022-01-15,mumbai,5,0,False
446,NaN,18,25000,it,invalid,mumbai,2,-1,True
635,USER_635,45,₹50000,it,2020/12/01,mumbai,5,3,True
395,USER_395,60,45000,HR,NaN,Bangalore,excellent,NaN,no
870,U1870,unknown,120000.75,IT,15/02/2021,Mumbai,1,five,NaN
475,NaN,NaN,₹50000,NaN,15/02/2021,Hyderabad,4,five,yes
382,USER_382,200,25000,it,NaN,Delhi,3,3,no
303,U1303,-5,NaN,Finance,15/02/2021,mumbai,poor,0,no

## 5

In [162]:
df['age'] = pd.to_numeric(df['age'],errors="coerce")
df.loc[(df['age']<0) | (df["age"]>100) ,"age"]=np.nan

df['age']

0       NaN
1      30.0
2      30.0
3       NaN
4       NaN
       ...
995    60.0
996     NaN
997     NaN
998     NaN
999    30.0
Name: age, Length: 1000, dtype: float64

## 6

In [ ]:
df['salary']=df['salary'].astype(str).str.replace("₹","",regex="False").replace("N/A",np.nan)
df['salary']= pd.to_numeric(df['salary'],errors="coerce")
df.sample(10)

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active
184,USER_184,45.0,50000.00,HR,NaN,NaN,poor,-1,no
783,NaN,25.0,50000.00,HR,NaN,Hyderabad,excellent,-1,True
370,USER_370,18.0,25000.00,Finance,2020/12/01,NaN,1,-1,no
689,NaN,60.0,120000.75,Sales,NaN,NaN,5,5,yes
99,NaN,45.0,NaN,HR,2020/12/01,Bangalore,5,-1,False
890,U1890,25.0,78000.00,HR,invalid,DELHI,1,10,True
8,USER_8,NaN,NaN,HR,invalid,mumbai,3,-1,yes
418,NaN,30.0,45000.00,HR,2020/12/01,Hyderabad,5,1,True
474,NaN,25.0,45000.00,NaN,2020/12/01,mumbai,4,5,True
327,NaN,60.0,45000.00,Finance,invalid,Bangalore,poor,5,True

## 7

In [164]:
df['join_date']=pd.to_datetime(df['join_date'],errors="coerce",dayfirst=True)

df['join_date']

0     2020-01-12
1            NaT
2            NaT
3            NaT
4            NaT
         ...
995          NaT
996          NaT
997          NaT
998          NaT
999          NaT
Name: join_date, Length: 1000, dtype: datetime64[ns]

In [165]:
df.head(10)

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active
0,USER_0,NaN,50000.00,HR,2020-01-12,DELHI,3,five,True
1,U1001,30.0,45000.00,Finance,NaT,Delhi,3,1,yes
2,U1002,30.0,25000.00,HR,NaT,Delhi,excellent,10,False
3,NaN,NaN,NaN,HR,NaT,Hyderabad,excellent,5,yes
4,NaN,NaN,120000.75,IT,NaT,DELHI,NaN,-1,False
5,USER_5,NaN,25000.00,IT,NaT,NaN,3,0,no
6,NaN,45.0,25000.00,NaN,NaT,mumbai,5,NaN,NaN
7,NaN,45.0,45000.00,NaN,NaT,Delhi,3,NaN,yes
8,USER_8,NaN,NaN,HR,NaT,mumbai,3,-1,yes
9,U1009,NaN,NaN,IT,NaT,Bangalore,poor,1,False

## 8

In [166]:
df['joining_year']=df['join_date'].dt.year
df['joining_year']

0      2020.0
1         NaN
2         NaN
3         NaN
4         NaN
        ...
995       NaN
996       NaN
997       NaN
998       NaN
999       NaN
Name: joining_year, Length: 1000, dtype: float64

## 9

In [167]:
df['department']=df['department'].str.strip().str.upper()
df['department']

0           HR
1      FINANCE
2           HR
3           HR
4           IT
        ...
995         HR
996         IT
997         HR
998        NaN
999         HR
Name: department, Length: 1000, dtype: object

## 10

In [168]:
df['city']=df['city'].str.upper()
df['city']

0          DELHI
1          DELHI
2          DELHI
3      HYDERABAD
4          DELHI
         ...
995        DELHI
996       MUMBAI
997       MUMBAI
998    BANGALORE
999    HYDERABAD
Name: city, Length: 1000, dtype: object

## 11

In [169]:
df['performance_score']=df['performance_score'].replace({"excellent": 5,"poor":0})
df['performance_score']=pd.to_numeric(df['performance_score'],errors="coerce")

df.sample(10)

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active,joining_year
562,NaN,NaN,25000.00,IT,NaT,DELHI,5.0,0,NaN,NaN
817,USER_817,18.0,45000.00,HR,NaT,DELHI,5.0,0,no,NaN
581,NaN,NaN,120000.75,IT,NaT,BANGALORE,5.0,1,NaN,NaN
640,NaN,18.0,120000.75,SALES,NaT,DELHI,0.0,-1,False,NaN
59,NaN,30.0,25000.00,NaN,NaT,MUMBAI,3.0,five,NaN,NaN
43,NaN,NaN,NaN,IT,NaT,DELHI,0.0,3,yes,NaN
996,U1996,NaN,NaN,IT,NaT,MUMBAI,NaN,5,no,NaN
510,USER_510,NaN,78000.00,FINANCE,NaT,BANGALORE,0.0,five,no,NaN
644,U1644,NaN,45000.00,NaN,NaT,DELHI,NaN,-1,yes,NaN
923,USER_923,NaN,45000.00,IT,NaT,BANGALORE,5.0,0,yes,NaN

## 12

In [170]:
df['experience_years']=df['experience_years'].replace({"five":5})
df['experience_years']=pd.to_numeric(df['experience_years'],errors="coerce")
df.loc[(df['experience_years']<0) ,"experience_years"]=np.nan

df['experience_years']

0       5.0
1       1.0
2      10.0
3       5.0
4       NaN
       ...
995     5.0
996     5.0
997     5.0
998     0.0
999     5.0
Name: experience_years, Length: 1000, dtype: float64

## 13

In [172]:
df['is_active']=df['is_active'].replace({"yes":True,"no":False})
df['is_active']=df['is_active'].astype("boolean")
df['is_active']

ValueError: Expected value of kwarg 'errors' to be one of ['raise', 'ignore']. Supplied value is 'coerce'

## 14

In [ ]:
df['user_id'].drop_duplicates(inplace=True)
df['user_id']

## 15

In [ ]:
df